#!/usr/bin/env sh
set -eux

BUILD_PACKAGES_DEPENDENCIES=curl
apk add --no-cache ${BUILD_PACKAGES_DEPENDENCIES}

curl -SLO https://github.com/phppgadmin2/phppgadmin/archive/master.zip
unzip master.zip
mv ./phpPgAdmin-master/* ${DOCKAGE_WEBROOT_DIR}
mv ${DOCKAGE_WEBROOT_DIR}/conf/config.inc.php-dist ${DOCKAGE_WEBROOT_DIR}/conf/config.inc.php
chown -R nginx:nginx ${DOCKAGE_WEBROOT_DIR}

rm -rf master.zip phppgadmin-master
apk del ${BUILD_PACKAGES_DEPENDENCIES}
