name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io
        docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/phppgadmin:latest
        docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/phppgadmin:latest
